import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Zuno",
    description: "Generated by Zuno AI Assistant with Gemini API",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" }
        ],
    },
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            {children}
        </>
    );
}
