import { Metadata } from "next";
import "../../globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "Zuno",
    description: "Generated by Zuno AI Assistant with Gemini API",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" }
        ],
    },
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <Toaster position="top-right" />
            {children}
        </>
    );
}
