import type { Metadata } from "next";

import { Outfit } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import { Analytics } from "@vercel/analytics/next"

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Zuno",
  description: "Generated by Zuno AI Assistant with Gemini API",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" }
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            loading: {
              duration: Infinity,
            },
            success: {
              duration: 5000,
            },
            error: {
              duration: 3000,
            },
          }}
        />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
