import { Metadata } from 'next';
import { ThemeProvider } from '@/context/ThemeContext';
import { SidebarProvider } from '@/context/SidebarContext';
import { Outfit } from 'next/font/google';
import AdminProvider from '@/components/admin/AdminProvider';
import '@/app/admin/css.css';

const outfit = Outfit({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Zuno Admin",
    description: "Generated by Zuno AI Assistant with Gemini API",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" }
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className={`${outfit.className} custom-scrollbar dark:bg-gray-900`}>
            <ThemeProvider>
                <SidebarProvider>
                    <AdminProvider>
                        {children}
                    </AdminProvider>
                </SidebarProvider>
            </ThemeProvider>
        </main>
    );
}
