// import AdminShell from "@/app/admin/_components/AdminShell";

// export default function AdminLayout({
//     children,
// }: {
//     children: React.ReactNode;
// }) {
//     // await requireSuperAdmin();
//     return (
//         <AdminShell>{children}</AdminShell>
//     );
// }



import { Toaster } from 'react-hot-toast';
import { Metadata } from 'next';
import { ThemeProvider } from '@/context/ThemeContext';
import { SidebarProvider } from '@/context/SidebarContext';
import { Outfit } from 'next/font/google';
import AdminProvider from '@/components/admin/AdminShell';
import './css.css';

const outfit = Outfit({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Zuno Admin Dashboard",
    description: "Generated by Zuno AI Assistant with Gemini API",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" }
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className={`${outfit.className} custom-scrollbar dark:bg-gray-900`}>
            <ThemeProvider>
                <Toaster
                    position="top-right"
                    toastOptions={{
                        loading: {
                            duration: Infinity,
                        },
                        success: {
                            duration: 5000, // success toast visible for 5s
                        },
                        error: {
                            duration: 3000,
                        },
                    }}
                />
                <SidebarProvider>
                    <AdminProvider>
                        {children}
                    </AdminProvider>
                </SidebarProvider>
            </ThemeProvider>
        </main>
    );
}
