import { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

import "@/app/globals.css";

export const metadata: Metadata = {
    title: "Zuno",
    description: "Generated by Zuno AI Assistant with Gemini API",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" }
        ],
    },
};

export default function UserLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            {/* Razorpay Script */}
            <Script
                src="https://checkout.razorpay.com/v1/checkout.js"
                strategy="afterInteractive"
            />
            <Toaster
                position="top-right"
                toastOptions={{
                    loading: {
                        duration: Infinity,
                    },
                    success: {
                        duration: 5000, // success toast visible for 5s
                    },
                    error: {
                        duration: 3000,
                    },
                }}
            />
            {children}
        </>
    );
}
